"use client";
import { useEffect, useState } from "react";

// const hostname = "ws://localhost:3000"
const hostname = "wss://substreams-sink-websockets-production.up.railway.app"
const ws = new WebSocket(hostname);

interface Data {
  chain: string;
  block: number;
  traceCalls: string
};

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xiSjIAI
 */
export default function Component() {
  const [messages, setMessages] = useState<Map<string, Data>>(new Map());
  const moduleHash = "0a363b2a63aadb76a525208f1973531d3616fbae";

  useEffect(() => {
    ws.onopen = () => {
      ws.send(JSON.stringify({
        id: Math.floor(Math.random() * 1000),
        method: "subscribe",
        params: {
            moduleHash
        }
    }));
    };
    ws.onmessage = event => {
      const json = JSON.parse(event.data);
      console.log(json)
      const { clock, manifest, data } = json;
      const chain = manifest?.chain;
      const topic = `${chain}:${moduleHash}`;
      if ( data ) setMessages((prevMessages) => {
        prevMessages.set(topic, {chain, block: clock.number, traceCalls: data.traceCalls});
        return new Map(prevMessages);
      });
    };
  }, [])
  const messagesArray = Array.from(messages.values());
  console.log({messages});

  return (
    <aside className="bg-black text-white p-6 rounded-lg w-full max-w-2xl font-mono">
      <div className="flex justify-between items-center">
        <div className="flex space-x-2 text-red-500">
          <div className="w-3 h-3 rounded-full bg-red-500" />
          <div className="w-3 h-3 rounded-full bg-yellow-500" />
          <div className="w-3 h-3 rounded-full bg-green-500" />
        </div>
        <p className="text-sm">Substreams WebSockets</p>
      </div>
      <div className="mt-4 break-normal">
        <p className="text-white-400">{hostname}</p><br />
        <p className="text-red-400">$ message {"<moduleHash>"}</p>
        <p className="text-green-400">$ {moduleHash}</p>
        {Array.from(messages.values()).map((data, index) => {
          return <p className="text-white" key={index}>{JSON.stringify(data, null, 2)}</p>
        })}
      </div>
    </aside>
  )
}
